- hosts: all
  become: yes
  tasks:
    - name: create the 'shamir' user
      user: name=shamir append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'shamir' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'shamir ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the shamir user
      authorized_key: user=shamir key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
